---
language: python
sudo: required
notifications:
  email: true
services: docker
env:
  global:
    - PACKER_VERSION="1.3.3"
before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -y dnsutils jq
  - pip install ansible ansible-lint molecule docker-py
  - wget https://releases.hashicorp.com/packer/${PACKER_VERSION}/packer_${PACKER_VERSION}_linux_amd64.zip
  - sudo unzip -o packer_${PACKER_VERSION}_linux_amd64.zip -d /usr/local/bin
  - packer --version
script:
  - make test