version: 0.2
env:
  PACKER_VERSION: "1.3.3"
phases:
  pre_build:
    commands:
      - sudo yum update -y && sudo yum install -y bind-utils
      - echo "Installing Packer"
      - curl -o packer.zip https://releases.hashicorp.com/packer/$PACKER_VERSION/packer_$PACKER_VERSION_linux_amd64.zip
      - sudo unzip -o packer.zip -d /usr/local/bin
      - echo "Validating Packer template"
      - pip install ansible ansible-lint molecule docker-py
      - packer validate template.json
  build:
    commands:
      - make ami | tee build.log
  post_build:
    commands:
      - egrep "${AWS_REGION}\:\sami\-" build.log | cut -d' ' -f2 > ami_id.txt
      - test -s ami_id.txt || exit 1
      - sed -i.bak "s//$(cat ami_id.txt)/g" ami_builder_event.json
      - aws events put-events --entries file://ami_builder_event.json
      - echo "build completed on `date`"
artifacts:
  files:
    - ami_builder_event.json
    - build.log
  discard-paths: yes