version: 0.2
env:
  variables:
    PACKER_VERSION: "1.3.3"
phases:
  pre_build:
    commands:
      - yum update -y && yum install -y bind-utils
      - echo "Installing Packer"
      - curl -o packer.zip "https://releases.hashicorp.com/packer/${PACKER_VERSION}/packer_${PACKER_VERSION}_linux_amd64.zip"
      - unzip -o packer.zip -d /usr/local/bin
      - echo "Validating Packer template"
      - pip install --upgrade pip setuptools
      - pip install ansible ansible-lint
      - packer -v
  build:
    commands:
      - make ami | tee build.log
  post_build:
    commands:
      - egrep "${AWS_REGION}\:\sami\-" build.log | cut -d' ' -f2 > ami_id.txt
      - test -s ami_id.txt || exit 1
      - sed -i.bak "s/<<AMI-ID>>/$(cat ami_id.txt)/g" unops_build_event.json
      - aws events put-events --entries file://unops_build_event.json
      - echo "build completed on `date`"
artifacts:
  files:
    - unops_build_event.json
    - build.log
  discard-paths: yes
