---
- name: install aws clients
  pip:
    name: "{{ item }}"
  loop:
    - https://s3.amazonaws.com/cloudformation-examples/aws-cfn-bootstrap-latest.tar.gz
    - awscli
  register: result
  until: result is succeeded
