---
packer_builder_type: ''
provider_name: "{{ 'aws' if packer_builder_type.startswith('amazon') else '' }}"

cwlogs_logs:
  - file: /var/log/messages
    group_name: "system_logs"
cwlogs_extra_logs: {}
cwlogs_stream_name: "{instance_id}"
cwlogs_aws_region: us-east-1
cwlogs_aws_loglevel: info
