---
- name: perform a yum update
  package:
    name: '*'
    update_cache: true
    update_only: true
  register: result
  until: result is succeeded
  when: common_upgrade_base | bool

- name: install baseline dependencies
  package:
    name: "{{ common_rpms }}"
    state: present
  register: result
  until: result is succeeded

- name: install extra rpms
  package:
    name: "{{ common_extra_rpm }}"
  register: result
  until: result is succeeded
  when: common_extra_rpms|length != 0

- name: Load br_netfilter kernel module
  modprobe:
    name: br_netfilter
    state: present

- name: Set sys.net.bridge.bridge-nf-call-iptables
  sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: 1
    sysctl_set: true
    state: present
    reload: true
