---
- name: install epel repository
  package:
    name: epel-release
    state: present
  register: result
  until: result is succeeded
  tags: ["gui", "installation"]

- name: desktop environment
  debug:
    msg: "Chosen desktop - {{ xrdp_desktop_env[xrdp_desktop].desktop }}"

- name: install desktop environment
  package:
    name: "{{ xrdp_desktop_env[xrdp_desktop].desktop }}"
    state: present
  when: xrdp_install_gui
  register: result
  until: result is succeeded
  tags: ["gui", "installation"]

- name: install xrdp
  package:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - xrdp
      - xrdp-devel
  register: result
  until: result is succeeded
  tags: ["gui", "installation"]

- name: install tigerVNC server
  package:
    name: tigervnc-server
    state: present
  register: result
  until: result is succeeded
  tags: ["gui", "installation"]

- name: start xrdp
  service:
    name: xrdp
    state: started
    enabled: true
  tags: ["gui", "installation"]

- name: change selinux context
  shell: |
    chcon --type=bin_t /usr/sbin/xrdp
    chcon --type=bin_t /usr/sbin/xrdp-sesman
  when: xrdp_install_gui
  tags: ["gui", "configuration"]

- name: global xsession file
  template:
    src: xsession.j2
    dest: /etc/skel/.xsession
    mode: "0755"
  notify: restart xrdp
  tags: ["gui", "configuration"]

- name: add xession to existing users' home dirs
  template:
    src: xsession.j2
    dest: "/home/{{ item.username }}/.xsession"
    owner: "{{ item.username }}"
    group: "{{ item.group | default(item.username) }}"
    mode: "0755"
  loop: "{{ xrdp_users }}"
  when: xrdp_users|length!=0
  tags: ["gui", "users"]

- name: upload xrdp.ini
  copy:
    src: xrdp.ini
    dest: /etc/xrdp/xrdp.ini
  notify: restart xrdp
  tags: ["gui", "configuration"]

- name: upload xrdp_keyboard.ini
  copy:
    src: xrdp_keyboard.ini
    dest: /etc/xrdp/xrdp_keyboard.ini
  notify: restart xrdp
  tags: ["gui", "configuration"]

- name: upload sesman.ini
  copy:
    src: sesman.ini
    dest: /etc/xrdp/sesman.ini
  notify: restart xrdp
  tags: ["gui", "configuration"]

- name: upload allow-colord.pkla
  copy:
    src: allow-colord.pkla
    dest: /etc/polkit-1/localauthority/50-local.d/allow-colord.pkla
  notify: restart xrdp
  tags: ["gui", "configuration"]
