---
- name: Add Docker dependencies
  package:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - device-mapper-persistent-data
      - lvm2
  register: result
  until: result is succeeded

- name: Add Docker repo
  yum_repository:
    name: docker
    description: Docker Yum repo
    baseurl: https://download.docker.com/linux/centos/7/$basearch/stable/
    gpgkey: https://download.docker.com/linux/centos/gpg
    gpgcheck: true
  register: result
  until: result is succeeded

- name: Install docker-py
  pip:
    name: docker-py
  register: result
  until: result is succeeded

- name: Install docker-compose
  pip:
    name: docker-compose
  register: result
  until: result is succeeded

- name: Install Docker-CE
  package:
    name: docker-ce
    state: present
  register: result
  until: result is succeeded

- name: Start Docker service
  service:
    name: docker
    enabled: true
    state: started

- name: Create Docker directory
  file:
    dest: /etc/docker
    state: directory

- name: Configure the Docker daemon
  template:
    src: "etc/docker/daemon.json"
    dest: /etc/docker/daemon.json
  notify:
    - restart docker

- name: Create service.d directory for config
  file:
    dest: /etc/systemd/system/docker.service.d
    state: directory
