---
- import_playbook: pre.yml

- name: build image
  hosts: all
  become: yes
  roles:
  - role: kernel
  - role: common
  - role: docker
  - role: providers
  - { role: users, tags: users }
  - { role: xrdp, tags: gui }
  - role: packer-cleanup

- import_playbook: post.yml

