---
- hosts: all
  gather_facts: false
  become: true
  pre_tasks:
  - name: run initial yum update
    package:
      name: '*'
      state: latest
      update_cache: true
      update_only: true
    register: result
    until: result is succeeded
