---
galaxy_info:
  author: Artur Sak
  description: User management role
  company: Two Point Inc.

  license: MIT

  min_ansible_version: 2.4

  platforms:
    - name: CentOS
      versions:
        - all

  galaxy_tags:
    - system
    - users
    - groups
    - management
    - configuration

  dependencies: []
